import Head from "next/head";
import { Inter } from "@next/font/google";
import { Flex, Heading } from "@chakra-ui/react";
import AboutMe from "../components/AboutMe";

const inter = Inter({ subsets: ["latin"] });

/* <Heading textAlign={"center"} size={"xl"}>
	This is My Portfolio!
</Heading> */
export default function Home() {
	return (
		<>
			<Head>
				<title>Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<AboutMe />
		</>
	);
}
