import Head from "next/head";
import { Inter } from "@next/font/google";
import {
	Box,
	Button,
	Flex,
	Heading,
	HStack,
	Image,
	Tag,
	Text,
} from "@chakra-ui/react";
import { NEXT_URL } from "@/config/config";
import { BsTerminal } from "react-icons/bs";
import { AiOutlineDown } from "react-icons/ai";
import ProjectCard from "@/components/ProjectCard";

const inter = Inter({ subsets: ["latin"] });

/* <Heading textAlign={"center"} size={"xl"}>
	This is My Portfolio!
</Heading> */

export default function Home({ url, projects }) {
	return (
		<>
			<Head>
				<title>Portfolio William Salas</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box id="aboutme" className="mainContainer " bg={"#323232"}>
				<Flex
					p={"30px"}
					color={"white"}
					className={"expandHeading"}
					pt={"50px"}
				>
					<h1>{"Let me introduce myself..."}</h1>
				</Flex>

				<Flex className="imageText" flexDirection={"row"} w={"100%"} h={"90vh"}>
					<Flex
						gap={"3px"}
						alignItems={"center"}
						flexDirection={"column"}
						w={"50%"}
					>
						<Box className="mainImage" mt={"70px"} w={"400px"} h={"400px"}>
							<Image
								rounded={"full"}
								objectFit={"contain"}
								src={url}
								alt="me"
							/>
						</Box>

						<Heading mt={"30px"} textAlign={"center"} color={"white"}>
							William Salas Bolaño
						</Heading>
						<HStack mt={"15px"}>
							<Tag>Full Stack Developer</Tag>
							<Tag colorScheme={"blue"}>React.js</Tag>
							<Tag colorScheme={"green"}>Node.js</Tag>
							<Tag colorScheme={"purple"}>Redux</Tag>
							<Tag colorScheme={"yellow"}>Javascript</Tag>
						</HStack>
					</Flex>
					<Flex
						flexDirection={"column"}
						margin={20}
						border={"1px solid gray"}
						borderRadius={"10px"}
						className="info"
						w={"50%"}
						h={"fit-content"}
						pb={20}
						overflow={"hidden"}
						bg={"#212121"}
					>
						<Flex
							flexDirection={"row"}
							justifyContent={"space-between"}
							p={2}
							w={"100%"}
							bg={"black"}
						>
							<BsTerminal color="white" />
							<Flex alignItems={"center"} gap={2}>
								<Box
									rounded={"full"}
									w={"10px"}
									h={"10px"}
									bg={"#F75D59"}
								></Box>
								<Box
									rounded={"full"}
									w={"10px"}
									h={"10px"}
									bg={"#FBBE2F"}
								></Box>
								<Box
									rounded={"full"}
									w={"10px"}
									h={"10px"}
									bg={"#29CD3F"}
								></Box>
							</Flex>
						</Flex>
						<Flex
							mt={"-px"}
							className="aboutText"
							gap={5}
							flexDirection={"column"}
						>
							<Text color={"white"} mx={20} mt={20}>
								{
									"> Hello! my name is William Salas, I'm 23 years old and i live in Barranquilla, Colombia."
								}
							</Text>
							<Text color={"white"} mx={20}>
								{
									"I'm a Full Stack Developer with training as an Architect and Graphic Designer."
								}
							</Text>
							<Text color={"white"} mx={20}>
								{
									"I Have experience working in React, Redux, Node, Express among other technologies commonly used in the market. I have a lot of affinity for the Front-End and the ability I have to incorporate my graphic and logical knowledge to develop a better user experience, I also have knowledge about the backend in Javascript. In general, I am a person who loves teamwork but I also have no problem with being a leader when required."
								}
							</Text>
							<Text color={"white"} mx={20}>
								{
									"I'm a realy easygoing person, willing to help others as much as eager to request help if needed, i'm a self-instructed musician and i love gaming in my free time."
								}
							</Text>

							<Button
								className="projectButton"
								mx={20}
								width={"fit-content"}
								rightIcon={<AiOutlineDown />}
							>
								<a href="#projects">know my projects</a>
							</Button>
						</Flex>
					</Flex>
				</Flex>
				<Flex
					flexDirection={"column"}
					id="projects"
					className="projects"
					w={"100%"}
					h={"100vh"}
					justifyContent={"space-between"}
				>
					<Box
						position={"absolute"}
						w={"100%"}
						h={"6%"}
						className={"fade"}
					></Box>
					<Flex flexDirection={"column"}>
						<Heading m={"90px"} color={"white"}>
							{" "}
							{">myProjects"}
						</Heading>
					</Flex>

					<Flex justifyContent={"space-around"}>
						{projects.map((p) => {
							return (
								<ProjectCard
									name={p.name}
									description={p.description}
									image={p.image}
									url={p.url}
									technologies={p.technologies}
									id={p.id}
									key={p.id}
								/>
							);
						})}
					</Flex>

					<Box
						alignItems={"flex-end"}
						w={"100%"}
						h={"6%"}
						className={"fadeDown"}
					></Box>
				</Flex>
				<Flex className="footer" h={"50px"} w={"100%"} bg={"#323232"}></Flex>
			</Box>
		</>
	);
}

export async function getStaticProps() {
	const response = await fetch(`${NEXT_URL}/image`);
	const projects = await fetch(`${NEXT_URL}/projects`);

	const data = await response.json();
	const projectsData = await projects.json();

	return { props: { url: data.url, projects: projectsData } };
}
